#!/usr/bin/env bash

# TODO: tidy up and generalize this

NAME=$1
PG=$2

lxc exec proxy -- rm /etc/apache2/upstream/${NAME}
lxc stop $N
lxc delete $N

lxc exec ${PG} -- dropdb $N
lxc exec ${PG} -- dropuser $N

sudo sed -i "/.* $N$/d" /etc/hosts
