#!/bin/env bash

CREDENTIALS_FILE=/usr/local/etc/dhis/.credentials.json
SERVICE=$1
USERNAME=$2

echo "SET ${SERVICE} CREDENTIALS"
echo "=============================="
echo "Do you want to add the password for the user ${USERNAME} in the service ${SERVICE}? (If not, password will be generated randomly)"
select yn in "Yes" "No"; do
    case $yn in
        Yes )
                        echo
                        echo "Please insert a password:"
                        read PASSWD
                        #echo $PASSWD
                        break;;
        No )
                        PASSWD=$(openssl rand -base64 12)
                        #echo "Password: ${PASSWD}"
                        break;;
    esac
done

#Save credentials
jq --arg service $SERVICE --arg username $USERNAME --arg password $PASSWD '.credentials[.credentials | length] |= . + {"name": $service,"username": $username,"password": $password}' ${CREDENTIALS_FILE} > ${CREDENTIALS_FILE}.tmp && mv ${CREDENTIALS_FILE}.tmp ${CREDENTIALS_FILE}
echo "Credentials saved to ${CREDENTIALS_FILE}"
echo "Service: ${SERVICE}"
echo "Username: ${USERNAME}"
echo "Password: ${PASSWD}"
sleep 15
