#!/bin/env bash

SERVICE=$1
PARENT=$(ps -o command= -p "$PPID" | awk '{print $2}')
VALID_SERVICES=$(lxc list -c n -f csv | grep -v 'postgres\|proxy' | tr '\n' ' ')

# Help text for this script
function usage {
  echo "Set credential for munin or glowroot"
  echo 
  echo "usage: dhis2-set-credential <SERVICE>"
  echo "  Valid services are: ${VALID_SERVICES}"
  echo
}

# Check Service
if [[ $SERVICE == "" ]];
then
  usage
  exit 1
fi

SERVICES=$(lxc list -c n -f csv)
IS_VALID_SERVICE=$(echo ${SERVICES} | grep ${SERVICE})

if [[ $IS_VALID_SERVICE == "" ]];
then
  echo "[ERROR] Service ${SERVICE} not found!"
  echo "Valid services are: ${VALID_SERVICES}"
  exit 1
else
  echo "[INFO] Service ${SERVICE} found"
  echo "SET ${SERVICE} CREDENTIALS"
  echo "=============================="
  echo "Do you want to add the password manually for the user admin in the service ${SERVICE}? (If not, password will be generated randomly)"
  select yn in "Yes" "No"; do
    case $yn in
      Yes )
        echo
        echo "Please insert a password:"
        read PASSWD
        break;;
      No )
        PASSWD=$(openssl rand -hex 12)
        break;;
    esac
  done

  if [[ $SERVICE == "monitor" ]];
  then
    htpasswd -b -c /tmp/.htpasswd admin ${PASSWD}
    lxc file push /tmp/.htpasswd monitor/etc/munin/.htpasswd
    lxc exec monitor -- chmod 644 /etc/munin/.htpasswd
    lxc exec monitor -- service apache2 restart
    rm /tmp/.htpasswd
    echo "Credentials have been set"
    echo "========================="
    echo "Service: monitor (munin)"
    echo "Username: admin"
    echo "Password: ${PASSWD}"
  else
    echo "Instance ${SERVICE} will be restarted. Are you sure do you want to continue?"
    select yn in "Yes" "No"; do
      case $yn in
        Yes )
          break;;
        No )
          exit 1;;
      esac
    done
    #Hash glowroot password
    GLOWROOT_SETUP=/usr/local/etc/dhis/glowroot-admin.json
    wget -P /tmp https://github.com/glowroot/glowroot/releases/download/v0.13.6/glowroot-central-0.13.6-dist.zip
    unzip -q -o /tmp/glowroot-central-0.13.6-dist.zip -d /tmp
    GLOWROOT_PASSWD_ENC=$(java -jar /tmp/glowroot-central/glowroot-central.jar hash-password $PASSWD)
    jq --arg context /${SERVICE}-glowroot '.web.contextPath=$context' $GLOWROOT_SETUP > /tmp/glowroot-admin.json.tmp
    jq --arg passwordHash $GLOWROOT_PASSWD_ENC '.users[].passwordHash=$passwordHash' /tmp/glowroot-admin.json.tmp > /tmp/glowroot-admin.json
    lxc file push /tmp/glowroot-admin.json $SERVICE/opt/glowroot/admin.json
    lxc exec $SERVICE -- chown -R tomcat.tomcat /opt/
    rm -rf /tmp/glowroot-central* /tmp/glowroot-admin.json*

    # Check if user wants to set credential
    if [[ $PARENT == "" ]];
    then
      lxc exec $SERVICE -- service tomcat9 restart
    fi
    echo "Credentials have been set:"
    echo "========================="
    echo "Instance: ${SERVICE}"
    echo "Service: ${SERVICE}-glowroot"
    echo "Username: admin"
    echo "Password: ${PASSWD}"
  fi
fi

